title: Augustin C. Hennings, PhD
url: https://achennings.github.io/index
# baseurl: "/index"
# remote_theme: achennings/achennings.github.io@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-176758942-1

footer: yes
footer_url: "https://github.com/achennings/achennings.github.io"
footer_text: "source"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "CV"
   link: "ACHennings_CV.pdf"
 - name: "Personal"
   link: "blog"
