title: Augustin C. Hennings
url: https://achennings.github.io
# baseurl: "/neuroscience"
# remote_theme: achennings/achennings.github.io@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/achennings"
footer_text: "pithy rejoinder"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "CV"
   link: "ACHennings_CV.pdf"
# - name: "Contact"
#   link: "contact"
